In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_table('WEOOct2020all.tsv')

In [6]:
df.head(3).T

,0,1,2
WEO Country Code,512,512,512
ISO,AFG,AFG,AFG
WEO Subject Code,NGDP_R,NGDP_RPCH,NGDP
Country,Afghanistan,Afghanistan,Afghanistan
Subject Descriptor,"Gross domestic product, constant prices","Gross domestic product, constant prices","Gross domestic product, current prices"
Subject Notes,Expressed in billions of national currency uni...,Annual percentages of constant price GDP are y...,Expressed in billions of national currency uni...
Units,National currency,Percent change,National currency
Scale,Billions,NaN,Billions
Country/Series-specific Notes,Source: National Statistics Office Latest actu...,"See notes for: Gross domestic product, consta...",Source: National Statistics Office Latest actu...
1980,NaN,NaN,NaN
1981,NaN,NaN,NaN
1982,NaN,NaN,NaN
1983,NaN,NaN,NaN
1984,NaN,NaN,NaN
1985,NaN,NaN,NaN
1986,NaN,NaN,NaN
1987,NaN,NaN,NaN
1988,NaN,NaN,NaN
1989,NaN,NaN,NaN
1990,NaN,NaN,NaN
1991,NaN,NaN,NaN
1992,NaN,NaN,NaN
1993,NaN,NaN,NaN
1994,NaN,NaN,NaN
1995,NaN,NaN,NaN
1996,NaN,NaN,NaN
1997,NaN,NaN,NaN
1998,NaN,NaN,NaN
1999,NaN,NaN,NaN
2000,NaN,NaN,NaN
2001,NaN,NaN,NaN
2002,453.484,NaN,178.756
2003,492.903,8.692,220.013
2004,496.209,0.671,246.210
2005,554.910,11.830,304.926
2006,584.658,5.361,345.817
2007,662.650,13.340,427.495
2008,688.247,3.863,517.509
2009,829.924,20.585,607.227
2010,899.956,8.438,711.759
2011,958.266,6.479,836.222
2012,"1,092.118",13.968,"1,033.591"
2013,"1,154.178",5.683,"1,116.827"
2014,"1,185.306",2.697,"1,183.039"
2015,"1,197.012",0.988,"1,226.570"
2016,"1,222.917",2.164,"1,222.917"
2017,"1,255.288",2.647,"1,285.460"
2018,"1,270.216",1.189,"1,327.690"
2019,"1,319.902",3.912,"1,469.596"
2020,"1,253.906",-5.000,"1,465.922"
2021,"1,304.063",4.000,"1,597.738"
2022,"1,363.060",4.524,"1,741.832"
2023,"1,424.397",4.500,"1,893.023"
2024,"1,481.497",4.009,"2,047.665"
2025,"1,540.937",4.012,"2,215.013"
Estimates Start After,2019,2019,2019
Unnamed: 56,NaN,NaN,NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8776 entries, 0 to 8775
Data columns (total 57 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   WEO Country Code               8776 non-null   object
 1   ISO                            8775 non-null   object
 2   WEO Subject Code               8775 non-null   object
 3   Country                        8775 non-null   object
 4   Subject Descriptor             8775 non-null   object
 5   Subject Notes                  8580 non-null   object
 6   Units                          8775 non-null   object
 7   Scale                          3900 non-null   object
 8   Country/Series-specific Notes  7589 non-null   object
 9   1980                           3879 non-null   object
 10  1981                           4008 non-null   object
 11  1982                           4049 non-null   object
 12  1983                           4091 non-null   object
 13  1984                           4116 non-null   object
 14  1985                           4192 non-null   object
 15  1986                           4228 non-null   object
 16  1987                           4249 non-null   object
 17  1988                           4338 non-null   object
 18  1989                           4399 non-null   object
 19  1990                           4888 non-null   object
 20  1991                           5045 non-null   object
 21  1992                           5428 non-null   object
 22  1993                           5621 non-null   object
 23  1994                           5748 non-null   object
 24  1995                           6104 non-null   object
 25  1996                           6247 non-null   object
 26  1997                           6412 non-null   object
 27  1998                           6584 non-null   object
 28  1999                           6662 non-null   object
 29  2000                           7071 non-null   object
 30  2001                           7193 non-null   object
 31  2002                           7289 non-null   object
 32  2003                           7323 non-null   object
 33  2004                           7391 non-null   object
 34  2005                           7428 non-null   object
 35  2006                           7433 non-null   object
 36  2007                           7441 non-null   object
 37  2008                           7452 non-null   object
 38  2009                           7472 non-null   object
 39  2010                           7475 non-null   object
 40  2011                           7477 non-null   object
 41  2012                           7484 non-null   object
 42  2013                           7493 non-null   object
 43  2014                           7523 non-null   object
 44  2015                           7545 non-null   object
 45  2016                           7547 non-null   object
 46  2017                           7551 non-null   object
 47  2018                           7547 non-null   object
 48  2019                           7539 non-null   object
 49  2020                           7501 non-null   object
 50  2021                           7449 non-null   object
 51  2022                           7389 non-null   object
 52  2023                           7371 non-null   object
 53  2024                           7371 non-null   object
 54  2025                           7371 non-null   object
 55  Estimates Start After          7585 non-null   float64
 56  Unnamed: 56                    0 non-null      float64
dtypes: float64(2), object(55)
memory usage: 3.8+ MB

In [8]:
df.shape

(8776, 57)

In [9]:
per_capita_df = df[df['Subject Descriptor']=="Gross domestic product per capita, constant prices"]

In [10]:
is_USD = df['Units'] == 'Purchasing power parity; 2017 international dollar'

In [80]:
per_capita_df['Units'].unique()

array(['National currency',
       'Purchasing power parity; 2017 international dollar'], dtype=object)

In [12]:
USD_df = per_capita_df[is_USD]

<ipython-input-12-88457d98e882>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  USD_df = per_capita_df[is_USD]

In [13]:
USD_df.shape

(195, 57)

In [15]:
USD_df['Country'].is_unique

True

In [16]:
USD_df['2019'] = USD_df['2019'].str.replace(',', '')
USD_df['2018'] = USD_df['2018'].str.replace(',', '')

<ipython-input-16-c2d80978d95f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  USD_df['2019'] = USD_df['2019'].str.replace(',', '')
<ipython-input-16-c2d80978d95f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  USD_df['2018'] = USD_df['2018'].str.replace(',', '')

In [17]:
USD_df['2019'] = pd.to_numeric(USD_df['2019'], errors='coerce')
USD_df['2018'] = pd.to_numeric(USD_df['2018'], errors='coerce')

<ipython-input-17-bdfcba05fbf3>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  USD_df['2019'] = pd.to_numeric(USD_df['2019'], errors='coerce')
<ipython-input-17-bdfcba05fbf3>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  USD_df['2018'] = pd.to_numeric(USD_df['2018'], errors='coerce')

In [26]:
is_null = USD_df['2019'].isnull()

In [27]:
USD_df[is_null]

,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,...,2018,2019,2020,2021,2022,2023,2024,2025,Estimates Start After,Unnamed: 56
7027,726,SOM,NGDPRPPPPC,Somalia,"Gross domestic product per capita, constant pr...",GDP is expressed in constant international dol...,Purchasing power parity; 2017 international do...,Units,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7567,463,SYR,NGDPRPPPPC,Syria,"Gross domestic product per capita, constant pr...",GDP is expressed in constant international dol...,Purchasing power parity; 2017 international do...,Units,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
USD_df = USD_df.dropna(subset=['2019'])

In [29]:
USD_df.shape

(193, 57)

In [30]:
USD_df['2018'].isnull().sum()

0

In [36]:
USD_df.dtypes

WEO Country Code                  object
ISO                               object
WEO Subject Code                  object
Country                           object
Subject Descriptor                object
Subject Notes                     object
Units                             object
Scale                             object
Country/Series-specific Notes     object
1980                              object
1981                              object
1982                              object
1983                              object
1984                              object
1985                              object
1986                              object
1987                              object
1988                              object
1989                              object
1990                              object
1991                              object
1992                              object
1993                              object
1994                              object
1995                              object
1996                              object
1997                              object
1998                              object
1999                              object
2000                              object
2001                              object
2002                              object
2003                              object
2004                              object
2005                              object
2006                              object
2007                              object
2008                              object
2009                              object
2010                              object
2011                              object
2012                              object
2013                              object
2014                              object
2015                              object
2016                              object
2017                              object
2018                             float64
2019                             float64
2020                              object
2021                              object
2022                              object
2023                              object
2024                              object
2025                              object
Estimates Start After            float64
Unnamed: 56                      float64
GDP grow 2019-2018               float64
dtype: object

In [32]:
USD_df['GDP grow 2019-2018'] = USD_df['2019'] - USD_df['2018']

<ipython-input-32-b1248a7b1ea0>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  USD_df['GDP grow 2019-2018'] = USD_df['2019'] - USD_df['2018']

In [33]:
USD_df.head(3).T

,7,52,97
WEO Country Code,512,914,612
ISO,AFG,ALB,DZA
WEO Subject Code,NGDPRPPPPC,NGDPRPPPPC,NGDPRPPPPC
Country,Afghanistan,Albania,Algeria
Subject Descriptor,"Gross domestic product per capita, constant pr...","Gross domestic product per capita, constant pr...","Gross domestic product per capita, constant pr..."
Subject Notes,GDP is expressed in constant international dol...,GDP is expressed in constant international dol...,GDP is expressed in constant international dol...
Units,Purchasing power parity; 2017 international do...,Purchasing power parity; 2017 international do...,Purchasing power parity; 2017 international do...
Scale,Units,Units,Units
Country/Series-specific Notes,"See notes for: Gross domestic product, consta...","See notes for: Gross domestic product, consta...","See notes for: Gross domestic product, consta..."
1980,NaN,"5,557.570","9,029.291"
1981,NaN,"5,757.860","9,019.899"
1982,NaN,"5,800.944","9,298.589"
1983,NaN,"5,741.680","9,489.245"
1984,NaN,"5,734.583","9,708.785"
1985,NaN,"5,533.616","9,779.107"
1986,NaN,"5,731.616","9,502.720"
1987,NaN,"5,573.342","9,194.247"
1988,NaN,"5,392.606","8,757.577"
1989,NaN,"5,764.051","8,954.995"
1990,NaN,"5,095.150","8,910.474"
1991,NaN,"3,690.689","8,590.352"
1992,NaN,"3,445.793","8,519.162"
1993,NaN,"3,799.703","8,146.850"
1994,NaN,"4,182.472","7,896.766"
1995,NaN,"4,582.933","8,035.779"
1996,NaN,"5,031.152","8,193.389"
1997,NaN,"4,509.656","8,146.907"
1998,NaN,"4,938.813","8,428.136"
1999,NaN,"5,610.886","8,564.895"
2000,NaN,"6,039.002","8,732.697"
2001,NaN,"6,601.497","8,864.497"
2002,"1,215.629","6,921.704","9,223.836"
2003,"1,269.090","7,331.760","9,741.889"
2004,"1,229.596","7,768.491","10,009.788"
2005,"1,328.474","8,239.877","10,442.594"
2006,"1,357.621","8,781.472","10,460.578"
2007,"1,481.751","9,377.489","10,651.478"
2008,"1,500.803","10,158.461","10,671.830"
2009,"1,763.843","10,570.197","10,637.821"
2010,"1,859.636","11,016.581","10,804.975"
2011,"1,919.777","11,327.429","10,886.398"
2012,"2,117.488","11,506.987","11,022.002"
2013,"2,164.844","11,643.598","11,093.337"
2014,"2,153.574","11,874.773","11,274.365"
2015,"2,111.764","12,173.644","11,443.134"
2016,"2,100.222","12,597.301","11,556.853"
2017,"2,102.784","13,088.307","11,458.757"
2018,2078.48,13654.8,11385.3
2019,2111.25,13944.4,11252.8
2020,"1,961.102","12,915.116","10,445.131"
2021,"1,993.691","13,724.042","10,584.812"
2022,"2,037.035","14,545.728","10,671.724"
2023,"2,080.842","15,197.035","10,619.484"
2024,"2,115.599","15,747.620","10,562.476"
2025,"2,151.006","16,313.618","10,504.567"
Estimates Start After,2019,2018,2019
Unnamed: 56,NaN,NaN,NaN
GDP grow 2019-2018,32.777,289.572,-132.504

In [45]:
sorted_USD_GDP_per_capita = USD_df.sort_values(by='GDP grow 2019-2018', ascending=False)

In [49]:
list(sorted_USD_GDP_per_capita['Country'].head(10).values)

['Ireland',
 'Estonia',
 'Lithuania',
 'Hungary',
 'Romania',
 'Poland',
 'Taiwan Province of China',
 'Libya',
 'Denmark',
 'Austria']

In [46]:
sorted_USD_GDP_per_capita.head(10)

,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,...,2019,2020,2021,2022,2023,2024,2025,Estimates Start After,Unnamed: 56,GDP grow 2019-2018
3607,178,IRL,NGDPRPPPPC,Ireland,"Gross domestic product per capita, constant pr...",GDP is expressed in constant international dol...,Purchasing power parity; 2017 international do...,Units,"See notes for: Gross domestic product, consta...","20,654.446",...,88227.656,"84,562.324","87,907.097","90,799.191","93,128.758","94,862.121","96,455.261",2019.0,NaN,3810.138
2437,939,EST,NGDPRPPPPC,Estonia,"Gross domestic product per capita, constant pr...",GDP is expressed in constant international dol...,Purchasing power parity; 2017 international do...,Units,"See notes for: Gross domestic product, consta...",NaN,...,36976.362,"35,035.621","36,602.446","37,957.399","39,184.076","40,383.137","41,628.140",2019.0,NaN,1683.825
4462,946,LTU,NGDPRPPPPC,Lithuania,"Gross domestic product per capita, constant pr...",GDP is expressed in constant international dol...,Purchasing power parity; 2017 international do...,Units,"See notes for: Gross domestic product, consta...",NaN,...,37021.250,"36,522.782","38,217.112","39,866.814","41,369.540","42,570.976","43,755.914",2019.0,NaN,1631.565
3337,944,HUN,NGDPRPPPPC,Hungary,"Gross domestic product per capita, constant pr...",GDP is expressed in constant international dol...,Purchasing power parity; 2017 international do...,Units,"See notes for: Gross domestic product, consta...","16,073.761",...,32612.668,"30,684.665","31,945.257","33,289.647","34,623.901","35,803.473","36,807.979",2019.0,NaN,1547.503
6352,968,ROU,NGDPRPPPPC,Romania,"Gross domestic product per capita, constant pr...",GDP is expressed in constant international dol...,Purchasing power parity; 2017 international do...,Units,"See notes for: Gross domestic product, consta...","13,386.966",...,29951.356,"28,515.475","29,821.708","30,981.311","32,148.488","33,323.418","34,494.403",2019.0,NaN,1358.753
6172,964,POL,NGDPRPPPPC,Poland,"Gross domestic product per capita, constant pr...",GDP is expressed in constant international dol...,Purchasing power parity; 2017 international do...,Units,"See notes for: Gross domestic product, consta...","12,311.028",...,33084.702,"31,919.160","33,414.056","34,958.674","36,284.702","37,399.429","38,350.352",2019.0,NaN,1320.632
7612,528,TWN,NGDPRPPPPC,Taiwan Province of China,"Gross domestic product per capita, constant pr...",GDP is expressed in constant international dol...,Purchasing power parity; 2017 international do...,Units,"See notes for: Gross domestic product, consta...","8,277.160",...,51112.948,"51,106.557","52,722.663","53,821.592","54,919.786","56,015.881","57,132.954",2019.0,NaN,1318.041
4417,672,LBY,NGDPRPPPPC,Libya,"Gross domestic product per capita, constant pr...",GDP is expressed in constant international dol...,Purchasing power parity; 2017 international do...,Units,"See notes for: Gross domestic product, consta...","99,828.945",...,13598.932,"4,490.087","7,825.324","12,004.710","12,968.455","12,878.476","12,789.387",2017.0,NaN,1100.218
2032,128,DNK,NGDPRPPPPC,Denmark,"Gross domestic product per capita, constant pr...",GDP is expressed in constant international dol...,Purchasing power parity; 2017 international do...,Units,"See notes for: Gross domestic product, consta...","31,935.906",...,57295.941,"54,665.181","56,469.947","57,753.074","58,783.738","59,641.396","60,473.445",2019.0,NaN,1073.431
412,122,AUT,NGDPRPPPPC,Austria,"Gross domestic product per capita, constant pr...",GDP is expressed in constant international dol...,Purchasing power parity; 2017 international do...,Units,"See notes for: Gross domestic product, consta...","31,380.125",...,56461.746,"52,418.014","54,580.452","55,474.322","56,272.490","56,969.908","57,619.535",2019.0,NaN,1050.809